### ISSUE TITLE
Lambda param when it doesn't fit in the same lane

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [facebook/ktfmt#165]
If the code with a lambda doesn't fit in a line the lambda parameter is moving down to the next line so:

```
veryLongBar {
    param ->
    doSomething(param)
}
```

1. I think it should add, at least, a break line between `param ->` and `doSomething`.

```
veryLongBar {
    param ->

    doSomething(param)
}
```

2. If it can be chained, the chain should have to have the priority

```
foo
    .bar
    .veryLongBaz { param ->
        doSomething(param)
    }
```

3. Another case to consider is when the lambda can fit in one line after the chain.

```
foo
    .bar
    .baz { param -> doSomething(param) }
```

A real example of this:

```
launchFragmentInContainer<SomeFragment>(themeResId = R.style.AppTheme).onFragment {
    fragment ->
    doSomething(fragment )
}
```

In this case, I think it should be reformated to

```
launchFragmentInContainer<SomeFragment>(themeResId = R.style.AppTheme)
    .onFragment { fragment -> doSomething(fragment ) }
```

Sorry for the indentation, I am writing this from mobile and the preview doesn't show the same indent as the markdown 😕

**Comment by cgrushko** [comment]
Thanks for the report! we'll take a look soon.
(I love that you considered and gave examples for multiple cases)

**Comment by JavierSegoviaCordoba** [comment]
I think there is another case where the arrow makes a break line alone. IMO in that case the parameter should be in the same line than the arrow.

**Comment by JavierSegoviaCordoba** [comment]
Another example, `test` is cut instead of format as chained calls with a break-line for each one:

![image](https://user-images.githubusercontent.com/7463564/106047493-f9386f00-60e3-11eb-8d84-56101222e09d.png)

It is strange because if I change the `Eagerly` enum to do not use the import so the sentence is a bit longer it is correctly formatted:

![image](https://user-images.githubusercontent.com/7463564/106047642-22f19600-60e4-11eb-9c02-288011d0d52a.png)

Maybe this is not the same problem but can be related.

**Comment by hick209** [comment]
As of v0.44 it is formatting as you suggested in the intro post
![image](https://github.com/facebook/ktfmt/assets/927983/e3d8d536-04f7-47dd-b15c-522514352fb2)

And for your last example, it now formats as this with 80 columns
![image](https://github.com/facebook/ktfmt/assets/927983/84cdc630-c827-45e8-908b-9dccad3f5b76)

And this with 100 columns
![image](https://github.com/facebook/ktfmt/assets/927983/a9c454ca-6368-47cf-bc02-861832eca51e)


I'm closing the issue here mostly because it's old and it looks like it's solved.
Feel free to reopen @JavierSegoviaCordoba
