### ISSUE TITLE
Unexpected infix formatting

### ISSUE THREAD

**Issue by ntkoopman** [facebook/ktfmt#217]
I have some code using the restassured library, which is using infix functions, and that currently get formatted very strangely because it uses infix functions.

```kt
val response =
    Given {
        accept(ContentType.JSON)
        header("foo", "bar")
    } When
        {
            get("/some/api")
        } Then
        {
            statusCode(HttpStatus.SC_INTERNAL_SERVER_ERROR)
        } Extract
        {
            body()
        }
```
expectation:
```kt
val response =
    Given {
        accept(ContentType.JSON)
        header("foo", "bar")
    } When {
        get("/some/api")
    } Then {
        statusCode(HttpStatus.SC_INTERNAL_SERVER_ERROR)
    } Extract {
        body()
    }
```

Optionally, for consistency this should probably apply to parentheses as well:

```kt
val foo =
    (34 + 34) + (
      someLongFunctionName() / anotherLongFunctionName() *
      superLongFunctionNameDefinitlyNeedANewLine()
    ) + (
      anotherLongFunctionName() + 3
    ) +
    superLongFunctionNameDefinitlyNeedANewLine()
```

Basically pulling the next bracket onto the same line following an infix call. This would break the rectangle rule, but seems more readable to me.

**Comment by hick209** [comment]
I get what you are saying and I actually agree with the statement (it's more readable to me as well).
Although this my opinion that is certainly not looking at all use cases.

> seems more readable to me

That's the part that makes this request complicated to act upon, since this is subjective.
Unless we know this won't affect other examples of code in an unexpected way AND we can can have an overall consensus that this is an improvement, it won't be something we plan on working.

I'd recommend trying to put a PR for this and I can test in our codebase what the changes are and could let you know whether we have all use cases here or not.

**Comment by hick209** [comment]
Closing issue as we will not act on it, feel free to submit a PR though as I have stated in the previous message
