### ISSUE TITLE
Wrong indentation for call with lambda argument and trailing call

### ISSUE THREAD

**Issue by ariofrio** [facebook/ktfmt#346]
ktfmt currently generates the following code (with 6 spaces of indentation between the first and second line):

```kotlin
runnable {
      // ...
    }
    .schedule()
```

If I remove the trailing call, it generates:

```kotlin
runnable {
  // ...
}
```

The generated code with the trailing call breaks the flow of the braces. In general a rule I expect is that the closing brace will be in the same column as the first character in the line where the opening brace is. Otherwise, the code looks like there might be a missing brace somewhere.

Instead of that weird indentation: any of the following would be acceptable:

```kotlin
runnable {
  // ...
}.schedule()
```
**^ The above might be ideal when there's only one trailing call.**

```kotlin
runnable {
  // ...
}
.schedule()
```

```kotlin
runnable {
  // ...
}
  .schedule()
```

```kotlin
runnable {
  // ...
}
    .schedule()
```

**Comment by ariofrio** [comment]
Notice that this is the opposite expectation than https://github.com/facebookincubator/ktfmt/issues/270. In that issue, they expected the closing brace to be indented further than the line of the opening brace, so they are in the same column as the trailing calls.

Possibly this behavior was an intended change in 0.31, but I can't seem to find the rationale behind it. Messing with the symmetry of the braces seems worse than not matching the closing brace with the trailing calls.

**Comment by att14** [comment]
I believe this is the same as #326.

> Yeah, this is expected, it's about avoiding "floating" in the chaining (so keep the closing parenthesis with the next .) and avoid confusing args with the next parts of the chain.

**Comment by hick209** [comment]
This was indeed an intentional change.

Maybe @davidtorosyan could provide more context if you still desire it

**Comment by davidtorosyan** [comment]
I don't think this was introduced in 0.31.

Here's some code formatted with 0.44 through 0.15:
```kt
class Foo {
  fun bar() {
    // sample 1
    runnable {
          someCode() // run
        }
        .schedule()

    // sample 2
    runnable {
      someCode() // run
    }
  }
}
```

And here's the same code formatted with 0.13 and earlier (note that 0.14 is missing):
```kt
class Foo {
  fun bar() {
    // sample 1
    runnable {
      someCode() // run
    }
        .schedule()

    // sample 2
    runnable {
      someCode() // run
    }
  }
}
```

I'm relatively sure this was done in c8b7b31f77d786f4c2b3ab622a1b93cea6561831 by @strulovich while working qualified expressions.

I also have the impression that this is due to the rectangle rule, and that doing it any other way would result in more issues. If anyone wants to look into this further, the easiest way might be to update the code and compare the unit tests before and after.

---

As a side note, to test this I had to download the jars from [maven](https://mvnrepository.com/artifact/com.facebook/ktfmt). It would be really nice if the [website](https://facebook.github.io/ktfmt/) supported multiple versions.
