### ISSUE TITLE
Documentation sublists are reformatted as code blocks

### ISSUE THREAD

**Issue by xeals** [facebook/ktfmt#365]
I have a doc commented formatted as follows:

```
/**
 * Overall comment.
 *
 * 1. Point 1
 *     - subpoint 1
 * 2. Point 2
 *     - subpoint 2
 */
```

GitHub (and most Markdown renderers, including IDEA's KDoc popup), will format this as an ordered list with two unordered sublists:

---
Overall comment.

1. Point 1
    - subpoint 1
2. Point 2
    - subpoint 2
---

ktfmt instead parses the 4-space indented sublists as code blocks, and fences them when reformatting:

````
Overall comment.

1. Point 1
```
    - subpoint 1
```
2. Point 2
```
    - subpoint 2
```
````

and now renders very differently:

---
Overall comment.

1. Point 1
```
    - subpoint 1
```
2. Point 2
```
    - subpoint 2
```
---

Unlike other Markdown parsers, IDEA only recognises list indentation with 4+ spaces (rather than 2), which conflicts with ktfmt. ktfmt's behaviour is also incorrect in my view, as no other tool I've used will parse sublists as code blocks.

Issue occurs with IDEA plugin 1.1.0.41 and with the 0.39 release JAR.

**Comment by davidtorosyan** [comment]
So I just tested it out in IDEA with this sample:
```kt
/**
 * Overall comment.
 *
 * 1. Point 1
 *  - one space
 * 2. Point 2
 *   - two spaces
 * 3. Point 3
 *    - three spaces
 * 4. Point 4
 *     - four spaces
 * 5. Point 5
 *      - five spaces
 */
class Test
```

Here's how it renders:

![image](https://user-images.githubusercontent.com/46736285/200966677-77d1758f-3139-441e-8745-60eeba632252.png)

And it looks like 3 spaces works just fine. That's great news because in v0.42 (not released yet) lists will be indented with three spaces: [KDocFormattingOptions.kt](https://github.com/facebook/ktfmt/blob/main/core/src/main/java/com/facebook/ktfmt/kdoc/KDocFormattingOptions.kt#L49)

Closing as fixed, we'll try to work out the remaining issues to get v0.42 out soon.

**Comment by xeals** [comment]
Cheers, will admit I only tested with two and four space indents since they're the most common.
