### ISSUE TITLE
Apparent inconsistencies in which lines are or aren't reformatted within a statement

### ISSUE THREAD

**Issue by kevinb9n** [facebook/ktfmt#388]
(This may be IDEA-plugin-specific, not sure.)

Here's a fun bug I had

```kotlin
  val allNodes: Set<Node> by lazy {
    setOf<Node>() +
        id +
        dependencies.map { it.typeExpr } +
        effectsRaw +
        defaults.allNodes  // only this line is modified
        extraNodes
  }
```

Note that if the formatter had reformatted this code properly I'd have caught the bug much more quickly than I did.

Here's what I'm seeing:

1. Hit "reformat code" keystroke in IDEA editor (with nothing selected): **does not** fix
2. Same but select *any character* in the file first: **does** fix
3. Right-click filename in Project pane, "reformat code", check "VCS only": **does not** fix
4. Right-click filename in Project pane, "reformat code", don't check "VCS only": **does** fix

What I would have expected is something like:

1. does fix (I assume the keystroke with nothing selected would mean the whole file or at least all changed lines)
2. fixes only if the selection includes the affected area
3. does fix
4. does fix

I also tried making a simpler kind of style error (an extra space before a paren) elsewhere in the file, and it was fixed in all four cases (even when the selected code was nowhere near the problem).

**Comment by davidtorosyan** [comment]
Hey @kevinb9n, thanks for reporting.

Before talking about the specific issues, I want to make sure we're talking about the same thing.

When I format with the [online tool](https://facebook.github.io/ktfmt/) (using java-like), I get this:
```kt
  val allNodes: Set<Node> by lazy {
    setOf<Node>() +
        id +
        dependencies.map { it.typeExpr } +
        effectsRaw +
        defaults.allNodes // only this line is modified
    extraNodes
  }
```

This is what you mean by "**does** fix", right?

---

I don't know a lot about the IDEA plugin, but my guess is that it only bothers reformatting if either (a) the file has changed, (b) you select a piece of code to format.

If that's true, then:
* (1) is expected (because nothing has changed)
* (2) is expected because you're explicitly formatting some code, and ktfmt always formats the whole file

I don't know what the VCS option means for (3) and (4).

**Comment by cgrushko** [comment]
I think the IDEA plugin is just old - I had trouble publishing the latest version due to some old APIs we're using.

**Comment by kevinb9n** [comment]
@davidtorosyan Correct, that is fixed.

When you say "if the file has changed", I have assumed this means "relative to VCS", in which case that line (commented at top) did change. Does it mean something else? Has changed since the last time I formatted?

**Comment by hick209** [comment]
IDE plugin was updated so I assume this was fixed. Closing
