### ISSUE TITLE
Unexpected removal of space after a comment

### ISSUE THREAD

**Issue by liutikas** [facebook/ktfmt#408]
# Repro steps

```bash
java  -cp /ssd/ssd5/androidx-main/prebuilts/androidx/external/com/facebook/ktfmt/0.44/ktfmt-0.44.jar:..all.jars com.facebook.ktfmt.cli.Main --kotlinlang-style Foo.kt
```

- Try to format the following file:
```kotlin
package com.tools.android

class Foo() {
    fun callMe() {
        onDispose { /* do nothing */ }
    }
}
```

# Expected
No changes

# Actual
The space after the `/* */` comment is removed resulting in
```kotlin
        onDispose { /* do nothing */}
```
without any space before `}`

**Comment by EmmanuelDav** [comment]
hey @hick209  I noticed this issue is still open, is it still available and can I work on it ??

**Comment by hick209** [comment]
Sorry the late response @EmmanuelDav, I was out on leave since September (new son).

Looks like @fredyw has already worked on this issue though on https://github.com/facebook/ktfmt/pull/426, but thank you so much for offering 😃

Next time you can feel free to just get started on the issue and submit a PR as we could always start the discussion from there
