### ISSUE TITLE
Missing jar for version 0.51

### ISSUE THREAD

**Issue by darioseidl** [facebook/ktfmt#491]
I recently adopted ktfmt and wanted to download the latest version, but the jar files linked in [release 0.51](https://github.com/facebook/ktfmt/releases/tag/v0.51) are from version 0.50 instead of 0.51.

Btw. The motivation to use ktfmt was to have no more formatting decisions and consistent formatting in different editors.
It's great in theory, but at the moment, because of this issue https://github.com/facebook/ktfmt/issues/490, version 0.50 and 0.51 result in very different formatting. The IntelliJ plugin already uses 0.51, but when we adopted ktfmt we formatted the code with 0.50, and we want to keep trailing spaces. 
It would be great, if v1.0 could be released with support for managing trailing spaces (enabled by default, afaiu?).
It would be even better, if ktfmt-gradle and the ktfmt IntelliJ plugin would allow specifying which version of ktfmt to use, to ensure that all tools use the same version of ktfmt.

**Comment by hick209** [comment]
Thanks for flagging the wrong jars, I've just fixed it.

Regarding the bug in the formatting, this should be fixed in 0.52 and it will also come with trailing comma management turned on (glimpse from 1.0).

Thanks for using ktfmt and thank you even more for flagging issues to us. Sorry that it took some time to get back to you on this one here, I was busy trying to ship Kotlin 2.0 for the organization.

**Comment by hick209** [comment]
v0.52 should come out later this week BTW

**Comment by sureshg** [comment]
@hick209 0.51 has some compatibility issue with spotless plugin. Any idea when the spotless plugin changes will be released?

**Comment by hick209** [comment]
@sureshg unfortunately I don't have visibility into that. I have fixed the compatibility issues, but they are not even on the 7.0 beta yet according to https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md 😕

Maybe worth opening an issue there regarding that.
