### ISSUE TITLE
[ktfmt_idea_plugin] Add support for format-on-save

### ISSUE THREAD

**Issue by Javi** [facebook/ktfmt#60]
On Jetbrains IDEs it's a very useful feature

**Comment by EmmanuelDav** [comment]
@hick209 can I work on this ?

**Comment by greyhairredbear** [comment]
Isn't that supported by IntelliJ (`Settings->Tools->Actions on Save`) itself? I have the ktfmt plugin `1.1.0.46` and IntelliJ ultimate `2023.2.5` and checked "reformat code" for kotlin files - this does the trick for me...

**Comment by hick209** [comment]
@EmmanuelDav, maybe check what @greyhairredbear mentioned here first.
In case you still believe a solution inside of the IDEA plugin would be more elegant feel free to submit a PR

**Comment by hick209** [comment]
Closing due to lack of response.
Feel free to reopen if that's still an issue for you

**Comment by maltejur** [comment]
> Isn't that supported by IntelliJ (`Settings->Tools->Actions on Save`) itself? I have the ktfmt plugin `1.1.0.46` and IntelliJ ultimate `2023.2.5` and checked "reformat code" for kotlin files - this does the trick for me...

From what I can tell, this will format the code with IntelliJ's own formatter. So it will possibly still use the approximate ktfmt [.editorconfig](https://github.com/Kotlin/ktfmt/blob/main/docs/editorconfig/.editorconfig-default), but not ktfmt directly. This leads to a very unfortunate situation, where the code is formatted correctly most of the time, but sometimes there are some subtle differences.

So having the option to run ktfmt directly on save would be very useful imo. And for reference, Prettier and other formatters/linters are also listed as a separate entry in the format on save list, so this seems to be a common pattern already:

<img width="994" height="730" alt="Image" src="https://github.com/user-attachments/assets/4f895882-bc6a-4f4b-b54b-295ffe2c00ae" />

> Closing due to lack of response. Feel free to reopen if that's still an issue for you

I don't have the needed permissions for that, but I would appreciate it if this issue was reopened.

**Comment by greyhairredbear** [comment]
I'm currently on ktfmt plugin version `1.3.0.64` and IntelliJ version `2026.2.0.1`. The configuration as I described it still works for me, and I'm 100% sure that it uses ktfmt. Changing the ktfmt formatting options also changes the format of a file on save for me. 

So I think the only reason to add this is to be more explicit about having ktfmt configured. I also use the autosave with another formatter plugin (Adapter for Eclipse formatter) and it also works like ktfmt. I suppose even the plugin for google-java-format works like that, since the ktfmt plugin has been based upon that. 

Maybe the trouble with your setup is that IntelliJ runs some `editorconfig` formatting after the ktfmt formatting? Or some stuff is done in the file watchers? Or some formatting step in the build process?

**Comment by maltejur** [comment]
Thanks for checking! I think you may be right, and I just got tripped up by weird IntelliJ behavior. It turns out when you press Ctrl+S in IntelliJ when you have made no changes from IntelliJ itself, it just doesn't try to reformat the code, even if it isn't in the correct format yet (maybe because you edited the file with a different editor). That is opposed to manually running the Reformat Code action, which always reformats the code. Because of this, I thought there was a difference in behavior between the format-on-save and the reformat action when it just didn't run any reformatter at all on save. Apologies for the confusion, and thanks again for the quick response.

**Comment by greyhairredbear** [comment]
Right, that makes sense. Happy to help ☺️
